### ISSUE TITLE
Is it possible to implement something like Yield Prolog in Elixir?

### ISSUE THREAD

**Issue by ponyatov** [sjakobi/elixir-for-prolog-problems#1]
Do you anytime hear about implementing something like this in Elixir?

http://yieldprolog.sourceforge.net/tutorial1.html

Elixir looks like very close, its match/bind looks native to the first section on YP manual.

**Comment by sjakobi** [comment]
Sorry, no idea.

Maybe you'll get a more helpful response on stackoverflow or https://www.reddit.com/r/elixir/.
